--------------------------------------------------------------------------------
Profile data file 'callgrind.out.callgrind_differ_help' (creator: callgrind-3.18.1)
--------------------------------------------------------------------------------
I1 cache: 
D1 cache: 
LL cache: 
Timerange: Basic block 0 - 154483
Trigger: Program termination
Profiled target:  ./../../target/release/callgrind_differ simple_small_high_threshold.cg --help (PID 70835, part 1)
Events recorded:  Ir
Events shown:     Ir
Event sort order: Ir
Thresholds:       95.0
Include dirs:     
User annotated:   
Auto-annotation:  off

--------------------------------------------------------------------------------
Ir               
--------------------------------------------------------------------------------
746,085 (100.0%)  PROGRAM TOTALS

--------------------------------------------------------------------------------
Ir               file:function
--------------------------------------------------------------------------------
59,053 ( 7.92%)  /home/lpv2013/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anstream-0.6.13/src/adapter/strip.rs:anstream::adapter::strip::next_bytes [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
51,828 ( 6.95%)  ./stdio-common/./stdio-common/vfscanf-internal.c:__vfscanf_internal [/usr/lib/x86_64-linux-gnu/libc.so.6]
42,561 ( 5.70%)  ./elf/./elf/dl-lookup.c:do_lookup_x [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
40,450 ( 5.42%)  ./elf/../sysdeps/x86_64/dl-machine.h:_dl_relocate_object
34,703 ( 4.65%)  ./elf/./elf/dl-lookup.c:_dl_lookup_symbol_x [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
28,245 ( 3.79%)  /home/lpv2013/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anstyle-parse-0.2.3/src/state/mod.rs:anstream::adapter::strip::next_bytes
27,427 ( 3.68%)  ./malloc/./malloc/malloc.c:_int_malloc [/usr/lib/x86_64-linux-gnu/libc.so.6]
26,276 ( 3.52%)  ./string/../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:__memcpy_avx_unaligned_erms [/usr/lib/x86_64-linux-gnu/libc.so.6]
25,320 ( 3.39%)  ./malloc/./malloc/malloc.c:_int_free [/usr/lib/x86_64-linux-gnu/libc.so.6]
24,430 ( 3.27%)  ./stdlib/../stdlib/strtol_l.c:____strtoul_l_internal [/usr/lib/x86_64-linux-gnu/libc.so.6]
22,609 ( 3.03%)  ./elf/./elf/do-rel.h:_dl_relocate_object
19,140 ( 2.57%)  ./elf/./elf/dl-tunables.c:__GI___tunables_init [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
14,257 ( 1.91%)  ./malloc/./malloc/malloc.c:malloc [/usr/lib/x86_64-linux-gnu/libc.so.6]
13,814 ( 1.85%)  ./string/../sysdeps/x86_64/strcmp.S:strcmp [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
12,004 ( 1.61%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/str/pattern.rs:clap_builder::builder::styled_str::StyledStr::replace_newline_var
 9,428 ( 1.26%)  /home/lpv2013/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anstyle-parse-0.2.3/src/state/definitions.rs:anstream::adapter::strip::next_bytes
 9,347 ( 1.25%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:anstream::adapter::strip::next_bytes
 9,081 ( 1.22%)  ./elf/./elf/dl-lookup.c:check_match [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
 8,492 ( 1.14%)  ./malloc/./malloc/malloc.c:realloc [/usr/lib/x86_64-linux-gnu/libc.so.6]
 7,304 ( 0.98%)  ./malloc/./malloc/malloc.c:free [/usr/lib/x86_64-linux-gnu/libc.so.6]
 7,294 ( 0.98%)  ./malloc/./malloc/malloc.c:_int_realloc [/usr/lib/x86_64-linux-gnu/libc.so.6]
 6,579 ( 0.88%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/slice/memchr.rs:core::slice::memchr::memchr_aligned [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
 6,250 ( 0.84%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/raw_vec/mod.rs:alloc::raw_vec::RawVecInner<A>::reserve::do_reserve_and_handle [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
 5,945 ( 0.80%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/fmt/mod.rs:core::fmt::write [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
 5,876 ( 0.79%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/fmt/mod.rs:core::fmt::Formatter::pad [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
 5,688 ( 0.76%)  /home/lpv2013/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anstyle-1.0.6/src/effect.rs:anstyle::style::Style::fmt_to
 5,565 ( 0.75%)  ./elf/./elf/dl-version.c:_dl_check_map_versions [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
 4,923 ( 0.66%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/iter/macros.rs:anstream::adapter::strip::next_bytes
 4,759 ( 0.64%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/non_null.rs:anstream::adapter::strip::next_bytes
 3,776 ( 0.51%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/raw_vec/mod.rs:_ZN5alloc7raw_vec11finish_grow17ha4acb4a325db170aE.llvm.7166644318285208313 [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
 3,729 ( 0.50%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:clap_builder::builder::styled_str::StyledStr::replace_newline_var
 3,725 ( 0.50%)  ./libio/./libio/iogetdelim.c:getdelim [/usr/lib/x86_64-linux-gnu/libc.so.6]
 3,648 ( 0.49%)  ./libio/./libio/genops.c:_IO_sputbackc [/usr/lib/x86_64-linux-gnu/libc.so.6]
 3,292 ( 0.44%)  ./malloc/./malloc/malloc.c:malloc_consolidate [/usr/lib/x86_64-linux-gnu/libc.so.6]
 3,242 ( 0.43%)  /home/lpv2013/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/clap_builder-4.5.2/src/output/textwrap/core.rs:clap_builder::output::textwrap::core::display_width
 3,085 ( 0.41%)  ./elf/../sysdeps/x86/dl-cacheinfo.h:intel_check_word.constprop.0 [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
 2,908 ( 0.39%)  /home/lpv2013/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anstream-0.6.13/src/adapter/strip.rs:_ZN8anstream7adapter5strip8next_str17h25f3f584adcbeb54E.llvm.18352387898321977320 [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
 2,724 ( 0.37%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/str/pattern.rs:<core::str::pattern::CharSearcher as core::str::pattern::Searcher>::next_match [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
 2,656 ( 0.36%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/alloc/unix.rs:_RNvCs691rhTbG0Ee_7___rustc11___rdl_alloc
 2,625 ( 0.35%)  /home/lpv2013/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anstyle-1.0.6/src/style.rs:anstyle::style::Style::fmt_to [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
 2,588 ( 0.35%)  /home/lpv2013/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/clap_builder-4.5.2/src/builder/arg.rs:clap_builder::builder::arg::Arg::stylize_arg_suffix [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
 2,421 ( 0.32%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/char/methods.rs:clap_builder::output::textwrap::core::display_width
 2,304 ( 0.31%)  ./libio/./libio/strops.c:_IO_str_init_static_internal [/usr/lib/x86_64-linux-gnu/libc.so.6]
 2,262 ( 0.30%)  ./elf/./elf/dl-load.c:_dl_map_object_from_fd [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
 2,222 ( 0.30%)  ./elf/../bits/stdlib-bsearch.h:intel_check_word.constprop.0
 2,156 ( 0.29%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/alloc/layout.rs:alloc::raw_vec::RawVecInner<A>::reserve::do_reserve_and_handle
 1,878 ( 0.25%)  ./string/../sysdeps/x86_64/multiarch/memchr-avx2.S:__memchr_avx2 [/usr/lib/x86_64-linux-gnu/libc.so.6]
 1,860 ( 0.25%)  ./elf/./elf/dl-cache.c:_dl_cache_libcmp [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
 1,792 ( 0.24%)  /home/lpv2013/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/clap_builder-4.5.2/src/builder/styled_str.rs:<clap_builder::builder::styled_str::StyledStr as core::fmt::Write>::write_str [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
 1,785 ( 0.24%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/str/pattern.rs:core::str::pattern::StrSearcher::new [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
 1,784 ( 0.24%)  /home/lpv2013/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/clap_builder-4.5.2/src/builder/arg.rs:_ZN75_$LT$callgrind_differ..args..Args$u20$as$u20$clap_builder..derive..Args$GT$12augment_args17hdea080b8cc91504eE.llvm.9636487036425525850
 1,750 ( 0.23%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/alloc/unix.rs:_RNvCs691rhTbG0Ee_7___rustc13___rdl_realloc
 1,712 ( 0.23%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/fmt/mod.rs:<str as core::fmt::Display>::fmt [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
 1,680 ( 0.23%)  ./stdio-common/./stdio-common/isoc99_sscanf.c:__isoc99_sscanf [/usr/lib/x86_64-linux-gnu/libc.so.6]
 1,646 ( 0.22%)  ./elf/./elf/dl-tunables.h:__GI___tunables_init
 1,613 ( 0.22%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:_ZN5alloc7raw_vec11finish_grow17ha4acb4a325db170aE.llvm.7166644318285208313
 1,470 ( 0.20%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/string.rs:<alloc::string::String as core::fmt::Write>::write_str [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
 1,465 ( 0.20%)  ./elf/../sysdeps/generic/dl-protected.h:do_lookup_x
 1,364 ( 0.18%)  ./elf/./elf/dl-deps.c:_dl_map_object_deps [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
 1,356 ( 0.18%)  ./string/../sysdeps/x86_64/multiarch/memchr-avx2.S:__rawmemchr_avx2 [/usr/lib/x86_64-linux-gnu/libc.so.6]
 1,345 ( 0.18%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/str/validations.rs:clap_builder::output::textwrap::core::display_width
 1,344 ( 0.18%)  /home/lpv2013/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/clap_builder-4.5.2/src/output/help_template.rs:clap_builder::output::help_template::HelpTemplate::write_args [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
 1,340 ( 0.18%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/slice/memchr.rs:core::slice::memchr::memrchr [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
 1,314 ( 0.18%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/slice/iter/macros.rs:core::fmt::write
 1,303 ( 0.17%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/slice/iter/macros.rs:core::slice::memchr::memrchr
 1,293 ( 0.17%)  ./nptl/./nptl/pthread_getattr_np.c:pthread_getattr_np@@GLIBC_2.32 [/usr/lib/x86_64-linux-gnu/libc.so.6]
 1,275 ( 0.17%)  ./elf/./elf/rtld.c:dl_main [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
 1,246 ( 0.17%)  ./malloc/./malloc/malloc.c:unlink_chunk.constprop.0 [/usr/lib/x86_64-linux-gnu/libc.so.6]
 1,230 ( 0.16%)  /home/lpv2013/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anstyle-parse-0.2.3/src/state/mod.rs:_ZN8anstream7adapter5strip8next_str17h25f3f584adcbeb54E.llvm.18352387898321977320
 1,207 ( 0.16%)  ./libio/./libio/genops.c:_IO_setb [/usr/lib/x86_64-linux-gnu/libc.so.6]
 1,161 ( 0.16%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/str.rs:alloc::str::join_generic_copy [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
 1,134 ( 0.15%)  ./libio/./libio/genops.c:_IO_no_init [/usr/lib/x86_64-linux-gnu/libc.so.6]
 1,129 ( 0.15%)  ./libio/./libio/genops.c:_IO_old_init [/usr/lib/x86_64-linux-gnu/libc.so.6]
 1,117 ( 0.15%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:clap_builder::builder::arg::Arg::stylize_arg_suffix
 1,080 ( 0.14%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/alloc/src/string.rs:<alloc::string::String as core::fmt::Write>::write_str [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
 1,052 ( 0.14%)  ./string/../sysdeps/x86_64/multiarch/memcmp-avx2-movbe.S:__memcmp_avx2_movbe [/usr/lib/x86_64-linux-gnu/libc.so.6]
 1,008 ( 0.14%)  ./stdio-common/../include/scratch_buffer.h:__vfscanf_internal
 1,008 ( 0.14%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/raw_vec/mod.rs:<clap_builder::builder::styled_str::StyledStr as core::fmt::Write>::write_str
 1,000 ( 0.13%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/alloc.rs:_RNvCs691rhTbG0Ee_7___rustc13___rdl_realloc [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   996 ( 0.13%)  ./malloc/./malloc/arena.c:free
   996 ( 0.13%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/spec_from_iter.rs:<alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   984 ( 0.13%)  ./elf/./elf/dl-misc.c:_dl_name_match_p [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   946 ( 0.13%)  ./elf/./elf/dl-load.c:open_verify.constprop.0 [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   922 ( 0.12%)  ./elf/./elf/dl-load.c:_dl_map_object [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   890 ( 0.12%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/raw_vec/mod.rs:clap_builder::builder::styled_str::StyledStr::indent
   883 ( 0.12%)  ./elf/../sysdeps/x86_64/dl-machine.h:_dl_start
   878 ( 0.12%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/ptr/non_null.rs:core::fmt::write
   876 ( 0.12%)  ./elf/./elf/dl-load.c:open_path [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   868 ( 0.12%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/num/uint_macros.rs:<core::str::pattern::CharSearcher as core::str::pattern::Searcher>::next_match
   861 ( 0.12%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/mod.rs:<&T as core::fmt::Display>::fmt [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   843 ( 0.11%)  ./stdlib/./stdlib/getenv.c:getenv [/usr/lib/x86_64-linux-gnu/libc.so.6]
   817 ( 0.11%)  ./elf/./elf/get-dynamic-info.h:_dl_map_object_from_fd
   815 ( 0.11%)  ./elf/./elf/do-rel.h:_dl_start
   806 ( 0.11%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/alloc/src/raw_vec/mod.rs:alloc::raw_vec::RawVecInner<A>::reserve::do_reserve_and_handle [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   805 ( 0.11%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/fmt/mod.rs:core::fmt::write'2 [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   789 ( 0.11%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/alloc/src/raw_vec/mod.rs:alloc::raw_vec::finish_grow [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   784 ( 0.11%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/cmp.rs:alloc::raw_vec::RawVecInner<A>::reserve::do_reserve_and_handle
   779 ( 0.10%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/fmt/rt.rs:core::fmt::write
   776 ( 0.10%)  ./malloc/./malloc/malloc.c:ptmalloc_init.part.0
   775 ( 0.10%)  ./elf/../sysdeps/generic/ldsodefs.h:do_lookup_x
   770 ( 0.10%)  ./elf/./elf/dl-minimal-malloc.c:__minimal_malloc [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   769 ( 0.10%)  ./elf/./elf/dl-object.c:_dl_new_object [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   768 ( 0.10%)  ./elf/./elf/dl-hwcaps.c:_dl_important_hwcaps [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   756 ( 0.10%)  ./malloc/./malloc/arena.c:realloc
   720 ( 0.10%)  ./stdio-common/../libio/strfile.h:__isoc99_sscanf
   715 ( 0.10%)  /home/lpv2013/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anstyle-1.0.6/src/style.rs:clap_builder::builder::arg::Arg::stylize_arg_suffix
   714 ( 0.10%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/io/stdio.rs:<std::io::stdio::StdoutLock as std::io::Write>::write_all [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   700 ( 0.09%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/slice.rs:alloc::slice::<impl [T]>::repeat [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   698 ( 0.09%)  ./elf/./elf/dl-tunables.c:__tunable_get_val [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   689 ( 0.09%)  ./elf/./elf/dl-cache.c:_dl_load_cache_lookup [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   688 ( 0.09%)  ./elf/./elf/dl-reloc.c:_dl_relocate_object [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   685 ( 0.09%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/memchr.rs:<core::str::pattern::CharSearcher as core::str::pattern::Searcher>::next_match
   666 ( 0.09%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/raw_vec/mod.rs:_ZN4core3ptr52drop_in_place$LT$clap_builder..builder..arg..Arg$GT$17h9c482e844997e4ebE.llvm.4102904063996710285
   652 ( 0.09%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/alloc.rs:_RNvCs691rhTbG0Ee_7___rustc13___rdl_dealloc [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   652 ( 0.09%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/alloc/unix.rs:_RNvCs691rhTbG0Ee_7___rustc13___rdl_dealloc
   629 ( 0.08%)  /home/lpv2013/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/clap_builder-4.5.2/src/builder/arg.rs:clap_builder::builder::arg::Arg::stylized [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   628 ( 0.08%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/io/buffered/bufwriter.rs:std::io::buffered::bufwriter::BufWriter<W>::flush_buf [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   610 ( 0.08%)  /home/lpv2013/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/clap_builder-4.5.2/src/output/help_template.rs:clap_builder::output::help_template::HelpTemplate::help [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   596 ( 0.08%)  ./elf/../sysdeps/x86/dl-cacheinfo.h:handle_intel.constprop.0 [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   588 ( 0.08%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:alloc::raw_vec::RawVecInner<A>::reserve::do_reserve_and_handle
   583 ( 0.08%)  /home/lpv2013/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/clap_builder-4.5.2/src/output/help_template.rs:clap_builder::output::help_template::HelpTemplate::spec_vals [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   556 ( 0.07%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/raw_vec/mod.rs:clap_builder::builder::arg::Arg::stylize_arg_suffix
   552 ( 0.07%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:_ZN8anstream7adapter5strip8next_str17h25f3f584adcbeb54E.llvm.18352387898321977320
   532 ( 0.07%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/raw_vec/mod.rs:<alloc::string::String as core::fmt::Write>::write_str
   530 ( 0.07%)  /home/lpv2013/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/clap_builder-4.5.2/src/builder/arg_group.rs:_ZN75_$LT$callgrind_differ..args..Args$u20$as$u20$clap_builder..derive..Args$GT$12augment_args17hdea080b8cc91504eE.llvm.9636487036425525850
   528 ( 0.07%)  ./string/../sysdeps/x86_64/multiarch/../strchr.S:index [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   528 ( 0.07%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/slice/iter/macros.rs:alloc::fmt::format::format_inner
   526 ( 0.07%)  /home/lpv2013/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/clap_builder-4.5.2/src/builder/command.rs:clap_builder::builder::command::Command::_build_self [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   523 ( 0.07%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/raw_vec/mod.rs:alloc::raw_vec::RawVec<T,A>::grow_one [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   520 ( 0.07%)  ./nptl/./nptl/libc-cleanup.c:__libc_cleanup_push_defer [/usr/lib/x86_64-linux-gnu/libc.so.6]
   519 ( 0.07%)  ./string/../sysdeps/x86_64/multiarch/strlen-vec.S:strlen [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   517 ( 0.07%)  ./string/../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:mempcpy [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   508 ( 0.07%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:<clap_builder::builder::styled_str::StyledStr as core::fmt::Write>::write_str
   504 ( 0.07%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/alloc/src/fmt.rs:alloc::fmt::format::format_inner [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   488 ( 0.07%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/raw_vec/mod.rs:clap_builder::output::help_template::HelpTemplate::spec_vals
   480 ( 0.06%)  ./elf/../sysdeps/generic/ldsodefs.h:_dl_relocate_object
   479 ( 0.06%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/num/uint_macros.rs:alloc::raw_vec::RawVecInner<A>::reserve::do_reserve_and_handle
   475 ( 0.06%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/raw_vec/mod.rs:clap_builder::output::help_template::HelpTemplate::help
   474 ( 0.06%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/alloc/src/raw_vec/mod.rs:<alloc::string::String as core::fmt::Write>::write_str
   470 ( 0.06%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:_ZN5alloc7raw_vec11finish_grow17ha4acb4a325db170aE.llvm.7166644318285208313
   464 ( 0.06%)  ./elf/../elf/dl-sysdep.c:_dl_sysdep_start [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   464 ( 0.06%)  ./string/../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S:memset [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   463 ( 0.06%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/raw_vec/mod.rs:clap_builder::output::help_template::HelpTemplate::write_args
   462 ( 0.06%)  /home/lpv2013/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/clap_builder-4.5.2/src/builder/styled_str.rs:<clap_builder::builder::styled_str::StyledStr as core::convert::From<&str>>::from [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   462 ( 0.06%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/intrinsics/mod.rs:clap_builder::builder::styled_str::StyledStr::indent
   458 ( 0.06%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/rt.rs:clap_builder::builder::arg::Arg::stylize_arg_suffix
   447 ( 0.06%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/macros/mod.rs:anstream::adapter::strip::next_bytes
   442 ( 0.06%)  ./elf/./dl-map-segments.h:_dl_map_object_from_fd
   437 ( 0.06%)  ./elf/./elf/dl-hwcaps_split.c:_dl_hwcaps_split_masked [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   423 ( 0.06%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/iter/macros.rs:_ZN8anstream7adapter5strip8next_str17h25f3f584adcbeb54E.llvm.18352387898321977320
   421 ( 0.06%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:clap_builder::builder::arg::Arg::stylize_arg_suffix
   420 ( 0.06%)  /home/lpv2013/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/clap_builder-4.5.2/src/builder/styling.rs:<clap_builder::builder::arg::Arg as core::fmt::Display>::fmt
   416 ( 0.06%)  ./nptl/./nptl/libc-cleanup.c:__libc_cleanup_pop_restore [/usr/lib/x86_64-linux-gnu/libc.so.6]
   405 ( 0.05%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/slice/iter/macros.rs:core::str::pattern::StrSearcher::new
   392 ( 0.05%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/intrinsics/mod.rs:alloc::raw_vec::RawVecInner<A>::reserve::do_reserve_and_handle
   384 ( 0.05%)  ./stdlib/../stdlib/strtol.c:__strtoul_internal [/usr/lib/x86_64-linux-gnu/libc.so.6]
   382 ( 0.05%)  ???:__cpu_indicator_init [/usr/lib/x86_64-linux-gnu/libgcc_s.so.1]
   378 ( 0.05%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/alloc/src/string.rs:<alloc::string::String as core::clone::Clone>::clone [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   376 ( 0.05%)  ./elf/./elf/dl-runtime.c:_dl_fixup [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   363 ( 0.05%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:clap_builder::output::help_template::HelpTemplate::spec_vals
   357 ( 0.05%)  /home/lpv2013/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/clap_builder-4.5.2/src/builder/arg.rs:clap_builder::builder::arg::Arg::_build [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   356 ( 0.05%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/io/buffered/linewritershim.rs:<std::io::stdio::StdoutLock as std::io::Write>::write_all
   355 ( 0.05%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/str/validations.rs:core::str::converts::from_utf8
   353 ( 0.05%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/non_null.rs:_ZN8anstream7adapter5strip8next_str17h25f3f584adcbeb54E.llvm.18352387898321977320
   351 ( 0.05%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:_ZN4core3ptr52drop_in_place$LT$clap_builder..builder..arg..Arg$GT$17h9c482e844997e4ebE.llvm.4102904063996710285 [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   350 ( 0.05%)  ./elf/../elf/dl-tls.c:_dl_allocate_tls_storage [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   348 ( 0.05%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/num/mod.rs:core::slice::memchr::memchr_aligned
   345 ( 0.05%)  ./io/../sysdeps/unix/sysv/linux/open64_nocancel.c:__open_nocancel [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   345 ( 0.05%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/str/mod.rs:clap_builder::builder::styled_str::StyledStr::replace_newline_var
   344 ( 0.05%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:clap_builder::output::help_template::HelpTemplate::write_args
   343 ( 0.05%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:<alloc::string::String as core::fmt::Write>::write_str
   342 ( 0.05%)  ./elf/./get-dynamic-info.h:dl_main
   339 ( 0.05%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/iter/macros.rs:clap_builder::output::textwrap::core::display_width
   336 ( 0.05%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/ptr/non_null.rs:core::slice::memchr::memrchr
   332 ( 0.04%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/alloc.rs:_RNvCs691rhTbG0Ee_7___rustc11___rdl_alloc [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   332 ( 0.04%)  ???:_RNvCs691rhTbG0Ee_7___rustc12___rust_alloc [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   326 ( 0.04%)  ???:_RNvCs691rhTbG0Ee_7___rustc14___rust_dealloc [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   320 ( 0.04%)  ./elf/./dl-find_object.h:_dl_find_object_from_map [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   315 ( 0.04%)  /home/lpv2013/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/clap_builder-4.5.2/src/builder/styled_str.rs:clap_builder::builder::styled_str::StyledStr::replace_newline_var [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   315 ( 0.04%)  /home/lpv2013/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/clap_builder-4.5.2/src/output/help_template.rs:clap_builder::output::help_template::option_sort_key [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   313 ( 0.04%)  ./elf/./elf/dl-fini.c:_dl_fini [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   312 ( 0.04%)  ./elf/./elf/dl-load.c:_dl_init_paths [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   312 ( 0.04%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/fmt/mod.rs:alloc::fmt::format::format_inner
   306 ( 0.04%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/iter/macros.rs:clap_builder::parser::parser::Parser::get_matches_with
   305 ( 0.04%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:clap_builder::output::help_template::HelpTemplate::write_args
   304 ( 0.04%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/result.rs:alloc::raw_vec::finish_grow
   302 ( 0.04%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/io/buffered/bufwriter.rs:<std::io::stdio::StdoutLock as std::io::Write>::write_all
   300 ( 0.04%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/str.rs:clap_builder::builder::styled_str::StyledStr::replace_newline_var
   299 ( 0.04%)  /home/lpv2013/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/clap_builder-4.5.2/src/builder/arg.rs:clap_builder::builder::arg::Arg::value_parser [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   299 ( 0.04%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/sync/once/futex.rs:std::sys::sync::once::futex::Once::call [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   298 ( 0.04%)  ./string/../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:memcpy [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   298 ( 0.04%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:clap_builder::builder::styled_str::StyledStr::indent
   297 ( 0.04%)  /home/lpv2013/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anstyle-parse-0.2.3/src/state/definitions.rs:_ZN8anstream7adapter5strip8next_str17h25f3f584adcbeb54E.llvm.18352387898321977320
   296 ( 0.04%)  ./elf/../sysdeps/x86/dl-prop.h:_dl_map_object_from_fd
   292 ( 0.04%)  ./misc/./misc/getauxval.c:getauxval [/usr/lib/x86_64-linux-gnu/libc.so.6]
   290 ( 0.04%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/str.rs:clap_builder::builder::styled_str::StyledStr::indent
   287 ( 0.04%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/slice/mod.rs:core::slice::memchr::memrchr
   285 ( 0.04%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/slice/index.rs:core::str::pattern::StrSearcher::new
   283 ( 0.04%)  ./elf/./elf/dl-environ.c:_dl_next_ld_env_entry [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   283 ( 0.04%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/non_null.rs:clap_builder::output::textwrap::core::display_width [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   280 ( 0.04%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/intrinsics/mod.rs:alloc::slice::<impl [T]>::repeat
   279 ( 0.04%)  ./signal/../sysdeps/unix/sysv/linux/libc_sigaction.c:__libc_sigaction [/usr/lib/x86_64-linux-gnu/libc.so.6]
   279 ( 0.04%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:clap_builder::builder::arg::Arg::stylized
   278 ( 0.04%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/alloc/src/vec/mod.rs:<alloc::string::String as core::fmt::Write>::write_str
   274 ( 0.04%)  ./elf/./elf/dl-sort-maps.c:_dl_sort_maps [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   268 ( 0.04%)  ./elf/./elf/dl-lookup-direct.c:_dl_lookup_direct [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   267 ( 0.04%)  ./libio/./libio/fileops.c:_IO_file_underflow@@GLIBC_2.2.5 [/usr/lib/x86_64-linux-gnu/libc.so.6]
   266 ( 0.04%)  /home/lpv2013/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/clap_builder-4.5.2/src/builder/arg.rs:<clap_builder::builder::arg::Arg as core::fmt::Display>::fmt [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   266 ( 0.04%)  /home/lpv2013/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/clap_builder-4.5.2/src/builder/styled_str.rs:<clap_builder::builder::arg::Arg as core::fmt::Display>::fmt
   266 ( 0.04%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:clap_builder::builder::styled_str::StyledStr::indent
   263 ( 0.04%)  ./malloc/./malloc/arena.c:malloc
   256 ( 0.03%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/intrinsics/mod.rs:<clap_builder::builder::styled_str::StyledStr as core::fmt::Write>::write_str
   253 ( 0.03%)  ./elf/./elf/dl-sort-maps.c:dfs_traversal.part.0 [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   251 ( 0.03%)  ./elf/./elf/dl-load.c:open_verify.constprop.1 [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   249 ( 0.03%)  /home/lpv2013/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/clap_builder-4.5.2/src/builder/command.rs:clap_builder::builder::command::Command::arg_internal [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   248 ( 0.03%)  ./elf/./elf/dl-minimal.c:strsep [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   246 ( 0.03%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/mod.rs:anstream::adapter::strip::next_bytes
   245 ( 0.03%)  ./elf/./elf/dl-tunables.c:__GI___tunable_set_val [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   244 ( 0.03%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:alloc::str::join_generic_copy
   243 ( 0.03%)  ./elf/./get-dynamic-info.h:_dl_start
   242 ( 0.03%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:clap_builder::output::help_template::HelpTemplate::help
   241 ( 0.03%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:<alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   238 ( 0.03%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/str.rs:clap_builder::output::help_template::HelpTemplate::spec_vals
   238 ( 0.03%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/rt.rs:clap_builder::output::help_template::HelpTemplate::write_args
   233 ( 0.03%)  ./string/../sysdeps/x86_64/strcspn.S:strcspn [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   232 ( 0.03%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/mod.rs:clap_builder::output::help_template::HelpTemplate::write_args
   232 ( 0.03%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:clap_builder::builder::styled_str::StyledStr::indent
   230 ( 0.03%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/slice/iter/macros.rs:core::fmt::write'2
   228 ( 0.03%)  /home/lpv2013/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anstream-0.6.13/src/strip.rs:anstream::strip::write_all [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   228 ( 0.03%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/string.rs:clap_builder::output::help_template::HelpTemplate::spec_vals
   224 ( 0.03%)  /home/lpv2013/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/clap_builder-4.5.2/src/builder/styled_str.rs:clap_builder::builder::styled_str::StyledStr::indent [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   224 ( 0.03%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/alloc/src/raw_vec/mod.rs:alloc::raw_vec::RawVec<T,A>::grow_one [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   223 ( 0.03%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:_ZN75_$LT$callgrind_differ..args..Args$u20$as$u20$clap_builder..derive..Args$GT$12augment_args17hdea080b8cc91504eE.llvm.9636487036425525850
   216 ( 0.03%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/sort/shared/smallsort.rs:_ZN4core5slice4sort6shared9smallsort11insert_tail17h0d598bd3836ccffeE.llvm.6010048971802147660 [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   215 ( 0.03%)  ./elf/../sysdeps/x86/dl-cacheinfo.h:get_common_cache_info.constprop.0 [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   210 ( 0.03%)  ./elf/./elf/dl-error-skeleton.c:_dl_catch_exception [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   210 ( 0.03%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/raw_vec/mod.rs:clap_builder::builder::styled_str::StyledStr::replace_newline_var
   210 ( 0.03%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/intrinsics/mod.rs:<alloc::string::String as core::fmt::Write>::write_str
   207 ( 0.03%)  ./elf/../sysdeps/x86/dl-cacheinfo.h:init_cpu_features.constprop.0
   207 ( 0.03%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/str/lossy.rs:<core::str::lossy::Utf8Chunks as core::iter::traits::iterator::Iterator>::next [/home/lpv2013/callgrind_differ/target/release/callgrind_differ]
   206 ( 0.03%)  ./elf/./elf/dl-find_object.c:_dlfo_process_initial [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   203 ( 0.03%)  ./elf/./elf/dl-init.c:call_init.part.0 [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
   197 ( 0.03%)  /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/slice/index.rs:core::fmt::write
   192 ( 0.03%)  ./libio/./libio/libioP.h:getdelim
   192 ( 0.03%)  ./stdio-common/./stdio-common/getline.c:getline [/usr/lib/x86_64-linux-gnu/libc.so.6]
   192 ( 0.03%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/str/iter.rs:clap_builder::builder::styled_str::StyledStr::indent
   191 ( 0.03%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:clap_builder::mkeymap::MKeyMap::_build
   191 ( 0.03%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:clap_builder::output::help_template::HelpTemplate::spec_vals
   188 ( 0.03%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:clap_builder::output::help_template::HelpTemplate::spec_vals
   184 ( 0.02%)  /home/lpv2013/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/clap_builder-4.5.2/src/builder/action.rs:clap_builder::builder::arg::Arg::_build
   184 ( 0.02%)  /home/lpv2013/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/cmp.rs:clap_builder::builder::styled_str::StyledStr::replace_newline_var

