--------------------------------------------------------------------------------
Profile data file 'callgrind.out.complex_medium' (creator: callgrind-3.18.1)
--------------------------------------------------------------------------------
I1 cache: 
D1 cache: 
LL cache: 
Timerange: Basic block 0 - 250757
Trigger: Program termination
Profiled target:  ./test_program_complex 1000 (PID 70768, part 1)
Events recorded:  Ir
Events shown:     Ir
Event sort order: Ir
Thresholds:       90.0
Include dirs:     
User annotated:   
Auto-annotation:  off

--------------------------------------------------------------------------------
Ir                 
--------------------------------------------------------------------------------
1,421,891 (100.0%)  PROGRAM TOTALS

--------------------------------------------------------------------------------
Ir                file:function
--------------------------------------------------------------------------------
334,377 (23.52%)  ./stdio-common/./stdio-common/vfprintf-internal.c:__vfprintf_internal [/usr/lib/x86_64-linux-gnu/libc.so.6]
219,071 (15.41%)  ./libio/./libio/genops.c:_IO_default_xsputn [/usr/lib/x86_64-linux-gnu/libc.so.6]
194,395 (13.67%)  test_program_complex.c:partition [/home/lpv2013/callgrind_differ/test_data/real_callgrind/test_program_complex]
 57,000 ( 4.01%)  ./libio/./libio/vsnprintf.c:__vsnprintf_internal [/usr/lib/x86_64-linux-gnu/libc.so.6]
 52,528 ( 3.69%)  ./stdio-common/./stdio-common/_itoa.c:_itoa_word [/usr/lib/x86_64-linux-gnu/libc.so.6]
 48,000 ( 3.38%)  ./libio/./libio/strops.c:_IO_str_init_static_internal [/usr/lib/x86_64-linux-gnu/libc.so.6]
 44,000 ( 3.09%)  ./libio/./libio/iopadn.c:_IO_padn [/usr/lib/x86_64-linux-gnu/libc.so.6]
 38,190 ( 2.69%)  ./string/../sysdeps/x86_64/multiarch/strchr-avx2.S:__strchrnul_avx2 [/usr/lib/x86_64-linux-gnu/libc.so.6]
 31,872 ( 2.24%)  ./stdlib/./stdlib/random_r.c:random_r [/usr/lib/x86_64-linux-gnu/libc.so.6]
 31,528 ( 2.22%)  ./elf/./elf/dl-lookup.c:do_lookup_x [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
 31,000 ( 2.18%)  ./debug/./debug/snprintf_chk.c:__snprintf_chk [/usr/lib/x86_64-linux-gnu/libc.so.6]
 24,024 ( 1.69%)  ./libio/./libio/genops.c:_IO_setb [/usr/lib/x86_64-linux-gnu/libc.so.6]
 23,170 ( 1.63%)  ./elf/./elf/dl-lookup.c:_dl_lookup_symbol_x [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
 23,000 ( 1.62%)  ./libio/./libio/genops.c:_IO_no_init [/usr/lib/x86_64-linux-gnu/libc.so.6]
 23,000 ( 1.62%)  ./libio/./libio/genops.c:_IO_old_init [/usr/lib/x86_64-linux-gnu/libc.so.6]
 21,000 ( 1.48%)  ./stdlib/./stdlib/random.c:random [/usr/lib/x86_64-linux-gnu/libc.so.6]
 19,140 ( 1.35%)  ./elf/./elf/dl-tunables.c:__GI___tunables_init [/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2]
 19,081 ( 1.34%)  ./stdio-common/../libio/libioP.h:__vfprintf_internal
 19,064 ( 1.34%)  ./stdio-common/./stdio-common/printf-parse.h:__vfprintf_internal
 19,014 ( 1.34%)  ./elf/../sysdeps/x86_64/dl-machine.h:_dl_relocate_object
 11,040 ( 0.78%)  test_program_complex.c:main [/home/lpv2013/callgrind_differ/test_data/real_callgrind/test_program_complex]

