--------------------------------------------------------------------------------
Profile data file 'callgrind.out.simple_large' (creator: callgrind-3.18.1)
--------------------------------------------------------------------------------
I1 cache: 
D1 cache: 
LL cache: 
Timerange: Basic block 0 - 4064923
Trigger: Program termination
Profiled target:  ./test_program_simple 2000 (PID 70730, part 1)
Events recorded:  Ir
Events shown:     Ir
Event sort order: Ir
Thresholds:       95.0
Include dirs:     
User annotated:   
Auto-annotation:  off

--------------------------------------------------------------------------------
Ir                  
--------------------------------------------------------------------------------
18,323,452 (100.0%)  PROGRAM TOTALS

--------------------------------------------------------------------------------
Ir                   file:function
--------------------------------------------------------------------------------
18,006,999 (98.27%)  test_program_simple.c:bubble_sort [/home/lpv2013/callgrind_differ/test_data/real_callgrind/test_program_simple]

